export const colors={
    heading:'#909090',
    button:'#6F45F0',
    buttonNonTint:'#909090',
    headerbackground:'#E9AEA0',
    ServiceProvider_buttonBackground:'#E9AEA0',
    headersubGround:"#C2D2F0",
    font1:"black",
    fontSubheadin:"#818187",
    background:"#F5F5F5",
    topbackground:'#DD9251',
    fontWhite:"#FFFFFF",
    Headingfont:'italic',
    FontWeight:"bold",
    serviceProviderStatus:"#BFE1AF",
    fontfaimly_heding:"Nunito-ExtraLight",
    fontfaimly_text:"Nunito-ExtraLight",
}